/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatsImport } from './routes/stats'
import { Route as SavedTextImport } from './routes/saved-text'
import { Route as PracticeImport } from './routes/practice'
import { Route as GuideImport } from './routes/guide'
import { Route as CustomTextImport } from './routes/custom-text'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const SavedTextRoute = SavedTextImport.update({
  id: '/saved-text',
  path: '/saved-text',
  getParentRoute: () => rootRoute,
} as any)

const PracticeRoute = PracticeImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRoute,
} as any)

const GuideRoute = GuideImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRoute,
} as any)

const CustomTextRoute = CustomTextImport.update({
  id: '/custom-text',
  path: '/custom-text',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/custom-text': {
      id: '/custom-text'
      path: '/custom-text'
      fullPath: '/custom-text'
      preLoaderRoute: typeof CustomTextImport
      parentRoute: typeof rootRoute
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideImport
      parentRoute: typeof rootRoute
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeImport
      parentRoute: typeof rootRoute
    }
    '/saved-text': {
      id: '/saved-text'
      path: '/saved-text'
      fullPath: '/saved-text'
      preLoaderRoute: typeof SavedTextImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-text': typeof CustomTextRoute
  '/guide': typeof GuideRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
  '/stats': typeof StatsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-text': typeof CustomTextRoute
  '/guide': typeof GuideRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
  '/stats': typeof StatsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-text': typeof CustomTextRoute
  '/guide': typeof GuideRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
  '/stats': typeof StatsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/custom-text'
    | '/guide'
    | '/practice'
    | '/saved-text'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom-text'
    | '/guide'
    | '/practice'
    | '/saved-text'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/custom-text'
    | '/guide'
    | '/practice'
    | '/saved-text'
    | '/stats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomTextRoute: typeof CustomTextRoute
  GuideRoute: typeof GuideRoute
  PracticeRoute: typeof PracticeRoute
  SavedTextRoute: typeof SavedTextRoute
  StatsRoute: typeof StatsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomTextRoute: CustomTextRoute,
  GuideRoute: GuideRoute,
  PracticeRoute: PracticeRoute,
  SavedTextRoute: SavedTextRoute,
  StatsRoute: StatsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/custom-text",
        "/guide",
        "/practice",
        "/saved-text",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/custom-text": {
      "filePath": "custom-text.tsx"
    },
    "/guide": {
      "filePath": "guide.tsx"
    },
    "/practice": {
      "filePath": "practice.tsx"
    },
    "/saved-text": {
      "filePath": "saved-text.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
