export const englishWrittingSentences = [
  {
    id: 1,
    text: "Climate change is caused mainly by human activities like burning coal, oil, and gas, which release harmful gases such as carbon dioxide into the atmosphere. These gases trap heat from the sun, making the Earth's temperature rise. This process is called global warming. Another major cause is deforestation—cutting down too many trees reduces the Earth’s ability to absorb carbon dioxide, making the air even dirtier. As a result, glaciers and ice caps in places like Antarctica and Greenland are melting, causing sea levels to rise. This leads to flooding in coastal cities, forcing people to leave their homes. Climate change also makes weather more extreme. Some areas experience heavy rainfall and floods, while others suffer from long droughts, making it hard to grow food. Wildfires are becoming more common, destroying forests and killing animals. Hurricanes and storms are getting stronger, damaging homes and cities. Many species of plants and animals are at risk of extinction because their natural habitats are changing too fast. People also suffer from heatwaves and air pollution, which lead to health problems. To slow down climate change, we must use clean energy like wind and solar power, plant more trees, and reduce waste. If we act together, we can protect our planet for future generations.",
    topic: "english-writting",
  },
  {
    id: 2,
    text: "Food adulteration happens when harmful or low-quality substances are added to food to increase profit. This is done by mixing cheap or harmful ingredients, using artificial colors, or adding chemicals to make food look fresh. For example, some traders mix water with milk, add harmful dyes to sweets, or use formalin to keep fish and fruits looking fresh for longer. These practices make food unsafe and can cause serious health problems. Eating adulterated food can lead to food poisoning, stomach pain, liver and kidney damage, and even deadly diseases like cancer. Children and elderly people are at higher risk because their bodies are weaker. Over time, consuming toxic food lowers immunity and reduces life expectancy. Food adulteration also affects the economy because unhealthy people cannot work properly, and medical costs rise. To stop this, strict laws must be enforced, and food sellers must be monitored. People should buy fresh and natural food, check labels, and avoid brightly colored or artificially glossy food. Awareness is key—everyone must learn about food safety and report dishonest sellers. Only by working together can we ensure safe and healthy food for all.",
    topic: "english-writting",
  },
  {
    id: 3,
    text: "Female education is very important because it helps women become independent, knowledgeable, and confident. When girls get an education, they can build better futures for themselves and their families. Educated women can work in different fields like medicine, teaching, business, and science, which helps a country grow. They also make better decisions about health, hygiene, and raising children, leading to healthier families and stronger societies. Unfortunately, in some places, girls still face barriers like poverty, early marriage, and social restrictions that stop them from going to school. Without education, many women are forced to depend on others and struggle to improve their lives. However, when girls are educated, they can break free from these limitations and help in the progress of their communities. Educated women also fight against injustice and stand up for their rights. Countries that invest in female education see lower child mortality rates, less poverty, and faster development. To ensure equal opportunities, governments and societies must work together to provide free and quality education for all girls. When women are educated, they can shape a better future, not just for themselves but for the entire world.",
    topic: "english-writting",
  },
  {
    id: 4,
    text: "Visiting the National Memorial in Savar was a memorable experience. This monument stands as a tribute to the brave souls who sacrificed their lives for Bangladesh’s independence in 1971. As I arrived, I was struck by the towering structure, symbolizing the courage and struggle of our freedom fighters. The vast green fields and the peaceful surroundings added to the solemn beauty of the place. Walking along the pathways, I saw the names of the martyrs inscribed on walls, reminding me of their immense sacrifice. The reflection of the monument in the water body nearby made the scene even more breathtaking. Many visitors were there, paying their respects and learning about the country’s history. The museum inside provided deeper insights into the Liberation War, showcasing pictures, artifacts, and documents from that time. Standing before the monument, I felt a deep sense of pride and gratitude for those who fought for our freedom. The visit was not just educational but also an emotional journey, making me realize the true cost of independence. The National Memorial in Savar is not just a structure—it is a symbol of our nation’s resilience and a place that every Bangladeshi should visit at least once.",
    topic: "english-writting",
  },
];
